# Permalinks
permalink:        pretty

# Setup
url:             http://mockham.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Zita V. Tóth

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      PhD Candidate in Philosophy (Fordham University)


# The tags listed as entries in the sidebar
sidebar_tags:     [Research, Teaching, Latin]

# Fallback image and color if not overwritten for tag or post
image:           /mockham/public/img/tree.jpg
color:            '#b14633'

author:
  name:           'Zita V. Tóth'
  facebook:     tothzit
  github:         mockham
  photo:          /mockham.github.io/public/img/zvt.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:
