# Permalinks
permalink:        pretty

# Setup
url:             http://zvtoth.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Zita V. Tóth

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      PhD Candidate in Philosophy (Fordham University)


# The tags listed as entries in the sidebar
sidebar_tags:     [Research, Teaching, Latin]

# Fallback image and color if not overwritten for tag or post
image:           /public/img/tree.jpg
color:            '#b14633'

author:
  name:           'Zita V. Tóth'
  email:           ztoth@fordham.edu
  facebook:     tothzit
  github:         zvtoth
  linkedin:      tothzit
  
  photo:          /public/img/zvt.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about: I am a PhD candidate and teaching fellow in philosophy at [Fordham University](http://www.fordham.edu), New York. My main interest is later medieval philosophy, especially metaphysics, philosophy of religion, and epistemology.
