# Permalinks
permalink:        pretty
markdown: kramdown

# Setup
url:             http://zvtoth.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Zita V. Tóth

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      Assistant Professor in Philosophy (Conception Seminary College)


# The tags listed as entries in the sidebar
sidebar_tags:     [Research, Teaching, Life]

# Fallback image and color if not overwritten for tag or post
image:           /public/img/tree.jpg
color:            '#b14633'

author:
  name:           'Zita V. Tóth'
  email:           ztoth@fordham.edu
  facebook:     zita.v.toth
  github:         zvtoth
  linkedin:      tothzita
  academia:   ZitaToth
  instagram:  oresmeember

  photo:          /public/img/zvt.jpg

  about: I am an Assistant Professor in philosophy at <a href = "http://www.conception.edu" target="_blank">Conception Seminary College</a>, Missouri. My main interests are later medieval philosophy, philosophy of religion, and metaphysics. <a href="zabout/">See more...</a>
